### ISSUE TITLE
Unused variable in ig.Music

### ISSUE THREAD

**Issue by Joncom** [phoboslab/Impact#13]
https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/impact/sound.js#L211

This variable doesn't get used anywhere.

**Comment by Joncom** [comment]
The variable `fadeTimer` should probably be renamed to `_fadeTimer` to match the original intent, and to be consistent with the naming convention used by all the other related private variables.

https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/impact/sound.js#L338

**Comment by gamecubate** [comment]
See #20 

**EDIT**
spareTimer... coding without coffee was such a good idea... Now fixed (i.e., _fadeTimer).

**Comment by gamecubate** [comment]
Can you do the merge and close this issue?

**EDIT**
New PR. #24
