### ISSUE TITLE
Unused argument in wm.EditEntities.loadEntitySettings

### ISSUE THREAD

**Issue by Joncom** [phoboslab/Impact#14]
https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/weltmeister/edit-entities.js#L381

**Comment by gamecubate** [comment]
See PR #21

**Comment by gamecubate** [comment]
Can you do the merge and close this issue?

**EDIT**
New PR. #25
