### ISSUE TITLE
Deleting an named entity in WM, then undoing, throws error

### ISSUE THREAD

**Issue by Joncom** [phoboslab/Impact#16]
Steps to reproduce:

1. Load any level
2. Select some entity
3. Give the entity a `name` property of any string, such as `"player"`
4. Delete the entity
5. Press "Z" to undo

An error was thrown in console.

This issue affects the "redo" code as well.

The reason this happens is because when a deleted entity has a name, this code gets executed when you undo the deletion:

https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/weltmeister/undo.js#L71

And there is no property called `namedEntities` in this class.

**Comment by Joncom** [comment]
I suspect the line is supposed to be:

`ig.game.entities.namedEntities[action.entity.name] = action.entity;`

**Comment by gamecubate** [comment]
Good catch. Fixes. PR #28 .

**Comment by Joncom** [comment]
Going to need the fix in the “redo” function too

**Comment by gamecubate** [comment]
I don’t think so. Tested + working without fail and without changes to redo function, once undo code changes applied.

==
Alexandre Rousseau
yalexr@gmail.com
+1.514.625.1964
http://alexr.ca

**Comment by Joncom** [comment]
Ah, yes, you are right. However, there is a closely related issue that is based on the same typo. I'll make a separate issue.

**Comment by Joncom** [comment]
Here it is: #29
