### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by dey-dey** [phoboslab/Impact#2]
Hey! I didn't see any tests, do you have a plan/opinion on how to start testing it?

**Comment by SHADOWELITE7** [comment]
It was already tested. He has created some games in it.
http://impactjs.com/

![image](https://user-images.githubusercontent.com/33847580/39625696-9e1c8fec-4f6c-11e8-9782-5e76eeb349b4.png)

**Comment by stepanvanzuriak** [comment]
@SHADOWELITE7  I'ts about testing like _Unit testing_

> Why should I spend more time on writing tests if my code seems to work fine? The answer is simple, it makes you think and reason better, as well as keeps your code easier to maintain and improves its accuracy.
https://codeburst.io/testing-your-javascript-code-95c171c71647

**Comment by SHADOWELITE7** [comment]
o I see :+1:

**Comment by mdxe** [comment]
This project was probably open sourced because it is not maintained anymore, so don't count on the original author to implement tests. You can try to submit a pull-request though.

**Comment by SHADOWELITE7** [comment]
makes sense since I knew the engine since I was 13 which was 4 years ago

**Comment by gamecubate** [comment]
I've been using ImpactJS for years now and I'm pretty sure that all bugs were ironed out long ago. New code or modules would benefit from TDD for sure, but the original stuff, not so much and I see no benefit for this. Just an opinion.

**Comment by SHADOWELITE7** [comment]
what is ``TDD``

**Comment by gamecubate** [comment]
TDD = [test-driven development](https://en.wikipedia.org/wiki/Test-driven_development)

**Comment by SHADOWELITE7** [comment]
thx
