### ISSUE TITLE
Selenium/Appium compatibility

### ISSUE THREAD

**Issue by Joskony** [phoboslab/Impact#3]
So, I once had to write some integration tests for a game made with impact.js. I didn’t create the game nor had I any knowledge of impact.

For these tests I was using Selenium and Appium. With Selenium I tried to click simple buttons inside the game. To my suprise that was not working. And at this point I’d just want to know if I judged the issue correctly and if there is a better workaround.

I wasn’t able to use Seleniums click method because the element I wanted to interact with was expecting something called ig.touchEvent. And as far as I understood the way Selenium works, is that it sends an HttpRequest to the browser to execute the according event, but since this event is not native to any browser Selenium could not do so? That’s atleast my explanation. My workaround for this was to simply the trigger this event on the according element through javascript, which works fine.

So is there another explanation and workaround for this case?

**Comment by gamecubate** [comment]
Selenium is useful for tests and assertion checks of DOM elements, but -- someone correct me if I'm wrong -- not for HTML5 canvas contents. But judging from [this](https://www.npmjs.com/package/phase-2-e), a need exists. Perhaps you could look at what phase-2-e did for Phaser and see if there is a way to develop similar [Nightwatch](http://nightwatchjs.org/) extensions for Impact.
