### ISSUE TITLE
Is it possible to trigger actions with midi data?

### ISSUE THREAD

**Issue by hellojoshgraham** [phoboslab/Impact#4]
I'm in the process of planning a music game, I was wondering if there was a way for impact.js to detect a midi note press instead of a computer keyboard press?

Thank you for your help!

**Comment by Xand0r** [comment]
I don't know! But in general, if it can be done with Javascript, you can do it with Impact. I'd do some searches to see if Javascript or HTML5 can help you in some way, not Impact specifically.

**Comment by gamecubate** [comment]
@hellojoshgraham I'd look on how to use Web MIDI API libs such as [webmidi](https://www.npmjs.com/package/webmidi) within Impact, optionally from within an adaptor class. 

That said, the idea of creating a ExternalInput class for ImpactJS is tempting. One could then subclass it for Web MIDI, MakeyMakey, and other concrete adaptor implementations.

This issue is a few months old, though. Are you still on this?

**Comment by hellojoshgraham** [comment]
Thanks @XandOr and @gamecubate for your help and comments!

I’m still on this actually! I did check out webmidi.js a little while ago and had a bit of a hacky go at it, but unfortunately couldn’t crack it yet! it must be possible... just getting the two frameworks to talk, and with very little latency.

Yes the idea of an ExternalInput class for ImpactJS is pretty exciting! so many possibilities!  

i’m building installations powered by arduino midi controllers at the moment, so the idea of being able to trigger input based music, sprites and all game elements gets me very excited!

thanks again for your help guys!

**Comment by gamecubate** [comment]
Impact has built-in functionality that makes class extensions and functionality injections easy. Simplest would be for you to clone the project and have a go at either creating a webmidi.js adaptor, or a plugin injecting the extra handler "sauce" into ig.Input.

If you need more advice for this, let us know some basic use cases.

NB: the [Impact forums](https://impactjs.com/forums), unfortunately now closed, would have been the perfect medium for this thread. I'll try and add a label or two to this thread, to see if it helps.
