### ISSUE TITLE
CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.

### ISSUE THREAD

**Issue by john-swana** [phoboslab/Impact#46]
What's the cause of this error , I scanned through the impact classes found nothing related
`CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.
`

**Comment by Joncom** [comment]
That’s just a warning, and not an actual error, correct?

**Comment by john-swana** [comment]
correct , I just got worried.
 what if  
image smoothing wasn't enabled
because 'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is depreciated

**Comment by Joncom** [comment]
I don't see `webkitImageSmoothingEnabled` anywhere in the Impact source code. Seems like maybe you have some custom code that was setting that somewhere...

**Comment by phoboslab** [comment]
It *is* set in Impact [here](https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/impact/system.js#L130) using [this beauty](https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/impact/impact.js#L180-L184).

All modern Browsers seem to support *some* of the CSS attributes now ([reference](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering#Browser_compatibility)), so `imageSmoothingEnabled` could be removed!?

**Comment by john-swana** [comment]
All of them except MS IE'
