### ISSUE TITLE
Diagonal Movement

### ISSUE THREAD

**Issue by Orrden** [phoboslab/Impact#5]
So, I'm not sure if this is the place to ask for help, but the forum redirected me here.  I'm attempted to make a top-down game.  I have movement for UP, LEFT, RIGHT, and DOWN, but I'm attempting to do Diagonal movement.  The code I have so far is this:

```
    //DIAGONAL-UP-RIGHT ATTEMPT//
    else if(ig.input.state('up') && ig.input.state('right')) {
      this.vel.y = -this.speed;
      this.vel.x = +this.speed;
    }
```

Seeemed logical to me, but unfortunately it didn't work.  Any advice?

**Comment by Xand0r** [comment]
The logic seems fine enough. You may need to post more code. I notice that the statement you included is an "else if." If you have a prior statement in this block that's true, this code won't get executed.

Post the rest of the code that you have that checks the other directions. The extra context should help diagnose this issue.
