### ISSUE TITLE
Scroll TileSet picker in WeltMeister?

### ISSUE THREAD

**Issue by rontrek** [phoboslab/Impact#54]
Is it possible to scroll the tileset picker when using taller tileset images? Zooming out shows the whole tileset, but too small to select the desired tile image.

**Comment by Joncom** [comment]
Currently I don’t think there is a way to do that, besides the “solution”
you already mentioned.

**Comment by rontrek** [comment]
I see and just managed to have the tileset reformatted horizontally which works to an extent and larger size.
