### ISSUE TITLE
Weltmeister start up issue

### ISSUE THREAD

**Issue by instantiator** [phoboslab/Impact#72]
A small issue, but when starting up vanilla Weltmeister, there's no `player.png` in the `media` folder and users see a frozen partial loading screen:
<img width="1678" alt="Screenshot 2019-12-06 at 12 21 06" src="https://user-images.githubusercontent.com/1856578/70323238-32e55100-1824-11ea-8262-32571089331c.png">

Adding `player.png` in the right place fixes this.

With developer tools open, an uncaught javascript error hints at the issue - but perhaps it could be made clearer what's going on for first time users? (I was baffled until I looked into it.)

**Comment by Joncom** [comment]
There should not be any player.png or reference to such a file in the vanilla Impact project. Literally the only thing the default project does is load and draw a font to the screen.

https://github.com/phoboslab/Impact/blob/master/lib/game/main.js

Are you certain you're running a vanilla project?
