### ISSUE TITLE
auto mine for impact minecraft cheat gui

### ISSUE THREAD

**Issue by LukasFullyLoaded** [phoboslab/Impact#74]
the command for adding my own custom blocks to the auto mine will not work help please

**Comment by Joncom** [comment]
What are you referring to? Sounds like you’re talking about custom code, so
if you don’t provide more details, no one will know what you’re talking
about.

**Comment by LukasFullyLoaded** [comment]
in minecraft im using a hack program called impact in it their is an auto mine option their is a code you can type in chat to add special ore{s} to this code but everytime i use it it doesnt work for instance it says to mine custom block(s) please do .b mine <block_name> <block_name> but when i use that command in the chat it never works

**Comment by Joncom** [comment]
You’re asking in the wrong place. This is Impact, the JavaScript game
engine, nothing to do with Minecraft.

**Comment by LukasFullyLoaded** [comment]
oh lmao sry for wasting your time

**Comment by K0-RR** [comment]
Somebody forgot to close this.
