### ISSUE TITLE
Trigger Question

### ISSUE THREAD

**Issue by yarnottc7892** [phoboslab/Impact#76]
I have question about Collision. So I am trying to do a trigger and I can't get the check function to work. On either of my objects, is there something I have to so to enable that? I am really confused on why it is not working. I followed the weltmeister guide on triggers and it is not working. I am attaching my trigger and player .js file. Any help is appreciated.

Trigger Code:
![TriggerCode](https://user-images.githubusercontent.com/55115161/73808121-672dad00-4794-11ea-86f8-dbf605c58b6b.PNG)

Player Code:
![PlayerCode](https://user-images.githubusercontent.com/55115161/73808116-639a2600-4794-11ea-89c1-f86093982bd3.PNG)

**Comment by Joncom** [comment]
Looks OK to me. So you’re expecting a message “it works” to be logged when
the player touches the trigger, but that never happens, right?

Can you enable debug draw boxes, and confirm that the player is in fact
colliding with the trigger visually?
