### ISSUE TITLE
ig.ua.mobile Not Working in Chrome on iOS

### ISSUE THREAD

**Issue by Donzo** [phoboslab/Impact#8]
Hello.

It appears that ig.ua.mobile is no longer working on Chrome on iOS.

Now the buttons won't draw(). 

I was thinking about just checking for screen width... Maybe that's a more resilient method.

**Comment by gamecubate** [comment]
Surprising discovery. On which iOS device did you observe this? I'll try and run a check.

**Comment by gamecubate** [comment]
On a MacBook Pro, in Chrome, with User-Agent set to Chrome iPhone, ig.ua.mobile is still found to be true. So will have to check this on a real device. Can you share (or Gist) some code (main.js, index.html, [style.css])?

![image](https://user-images.githubusercontent.com/1483884/47967061-8684da00-e027-11e8-8feb-8598f6bff3a2.png)

**Comment by Donzo** [comment]
I’m sorry, it’s possible that I misdiagnosed it.

Here are two pictures showing what I’m experiencing:

One picture is my game loaded on Chrome, the other is on Safari.

The buttons don’t draw on Chrome, I presumed because ig.ua.mobile was not
working.

It may be something else.

I will look at it more on Monday.

**Comment by Donzo** [comment]
My mistake. I tested it as well.
Something else has caused my issue. 

I will explore it further.

**Comment by Donzo** [comment]
Yeah, I was having this issue:

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080

With the touch-button.js plugin.

I commented out the preventDefault() call in the touchStart function and the buttons started drawing again.

My mistake...
