### ISSUE TITLE
Weltmeister Start up

### ISSUE THREAD

**Issue by smallcpu** [phoboslab/Impact#82]
Hello, I am having an issue with the start up of vanilla Weltmeister, it seems the tool is not opening all the way and I have a blank page with no functionality. 

![image](https://user-images.githubusercontent.com/29586968/86516879-04dfe380-bdea-11ea-884f-ae3980f7ae0d.png)

Here is the error that I am getting
![image](https://user-images.githubusercontent.com/29586968/86516892-1628f000-bdea-11ea-8af9-8b05c77e09dc.png)

Hope there is a solution with this!! Thank you

**Comment by Joncom** [comment]
You need to serve the page from a web server that supports PHP. Or you
could serve it from NodeJS with
https://github.com/drhayes/impact-dev-server

**Comment by smallcpu** [comment]
> You need to serve the page from a web server that supports PHP. Or you could serve it from NodeJS with https://github.com/drhayes/impact-dev-server

Oh yes the page is running in a web server that supports php.

**Comment by Joncom** [comment]
Did that fix the issue?

**Comment by phoboslab** [comment]
It seems the PHP notice about `get_magic_quotes_gpc` is screwing up the JSON result from the API. I guess this could be safely removed:

https://github.com/phoboslab/Impact/blob/master/lib/weltmeister/api/config.php#L7-L20

It's a relic from when PHP4 was still somewhat in use. Maybe replace with a check that ensures that `phpversion()` is at least 5 - though that's probably unnecessary. PHP5 was released 16 years ago.

**Comment by smallcpu** [comment]
It worked! Thank you so much!!
