### ISSUE TITLE
secure or delete forum account

### ISSUE THREAD

**Issue by trusktr** [phoboslab/Impact#85]
Hello!

Google Password's data breach says I should change my impactjs account password. I'm guessing it is the old forums.

My account on there is [`trusktr`](https://impactjs.com/forums/user/trusktr). Is it possible to change the password?

Is it possible for anyone to log in? If not, then perhaps I just delete my password and all good.

**Comment by phoboslab** [comment]
impactjs.com is entirely read only now and has been for a few years. There's no way to log in to the forums.

I assume you re-used the same password on another site that had a data breach?

In an abundance of caution, I have overwritten all the password hashes in the database with new random hashes now. Meaning that even if someone gained direct access to the database on impactjs.com, they wont find the original password hashes.

**Comment by trusktr** [comment]
Sweet. Thanks a lot!
