### ISSUE TITLE
cannot open

### ISSUE THREAD

**Issue by GhostieKoto** [phoboslab/Impact#93]
double-clicking index.html (to open the editor or whatever) opens it in the browser however it's forever loading it doesn't do anything else.

**Comment by Joncom** [comment]
You need to open index.html served through a web server, which would look something like http://localhost/index.html

Instead of simply double clicking on index.html, which would look something like: file:///path/to/index.html

**Comment by GhostieKoto** [comment]
you wanna explain?

Like, what do I do to get to the web server or whatever?

**Comment by Joncom** [comment]
Have a look here:

https://impactjs.com/documentation/getting-started

**Comment by GhostieKoto** [comment]
Oh ok
