### ISSUE TITLE
Weltmeiser not working

### ISSUE THREAD

**Issue by maverickteckh** [phoboslab/Impact#94]
When I try and launch the editor I get a few errors! Nothing is working and im dum :/

**Comment by Joncom** [comment]
Have you had it working in the past, or is this your first time setting things up? What have you tried so far?

**Comment by Joncom** [comment]
What specific errors are you seeing?

**Comment by maverickteckh** [comment]
I have not seen it working 
Errors below:
![image](https://user-images.githubusercontent.com/74848706/229590661-81fd10d3-db69-4c50-92bb-15ea1b5a0965.png)

**Comment by Joncom** [comment]
Looks like your web server may not be processing PHP files as PHP. Have you followed the instructions here?

https://impactjs.com/documentation/getting-started

**Comment by maverickteckh** [comment]
hmm OK! i will try

**Comment by maverickteckh** [comment]
Originally I was running it on github pages, but now I ran it on replit(Has php) and I got the same errors!

**Comment by maverickteckh** [comment]
I might just write my game from scratch then.

**Comment by Joncom** [comment]
I’m not so familiar with Replit.

Maybe try using one of the web servers suggested in the link above (ex. XAMMP).

**Comment by phoboslab** [comment]
Works for me: https://replit.com/@phoboslab/Impact
Steps: create a new repl with PHP, put Impact sources in there, press play.

Or, you can just clone this repl :)

**Comment by maverickteckh** [comment]
Ok THANKS!
